apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: db-pool
      containers:
        - image: registry.hub.docker.com/library/postgres:9.6
          name: postgres
          resources:
            requests:
              cpu: 800m
            limits:
              cpu: 800m
          env:
            - name: POSTGRES_DB
              value: fsi_production
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database_password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
              # This name must match the volumes.name below.
            - name: postgres-db-data
              mountPath: "/usr/local/pgsql/data"
      volumes:
        - name: postgres-db-data
          gcePersistentDisk:
            # This disk must already exist.
            pdName: db-data
            fsType: ext4